### ISSUE TITLE
Question about queries

### ISSUE THREAD

**Issue by Pesti-wustl** [Creepysin-Studios/Wiki.Net#7]
Sorry, not an issue but I am not sure where else to ask. But I am curious, how do you make the url with the parameters format correctly? From my understanding, a url has parameters separated by a &, but I don't see anything in your code that does so. I am new to APIs, so it may be something obvious!

**Comment by Voltstro** [comment]
It is done by using a [FormUrlEncodedContent](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.formurlencodedcontent?view=net-6.0), and a string.format.

https://github.com/Voltstro-Studios/Wiki.Net/blob/cadbe5e1edd2617936535d43e02cb36663f2c0fa/src/Wiki.Net/WikiSearcher.cs#L89-L92
